root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/go-server ."
  entrypoint = "./tmp/go-server"
  include_ext = ["go"]
  exclude_dir = ["tmp", ".git", "handlers/testdata"]
  exclude_regex = ["_test.go"]
  delay = 200
  stop_on_error = true
  send_interrupt = true

[log]
  time = true

[misc]
  clean_on_exit = true
